version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_graphql
    restart: always
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
